env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
  - next/core-web-vitals
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'import/extensions': off
  'react/jsx-filename-extension':
    - error
    - extensions:
        - '.tsx'
  'react/jsx-props-no-spreading': 'off'
  'no-unused-vars': off
  'no-shadow': off
