version: 2.1

executors:
  node:
    docker:
      - image: node:18.14.0

commands:
  install_dependencies:
    description: 'Install the Dev Dependencies required for the jobs.'
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: 'Install Dev Dependencies'
          command: npm i -D
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
  generate_release:
    executor: node
    steps:
      - checkout
      - run:
          name: 'Generate Release'
          command: |
            npm i -g @semantic-release/changelog @semantic-release/git semantic-release
            semantic-release

  linter:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: 'Run Linter'
          command: npm run lint

  test:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: 'Run Tests'
          command: npm test

workflows:
  version: 2

  development:
    jobs:
      - linter:
          filters:
            branches:
              only: main
      - test:
          filters:
            branches:
              only: main
      - generate_release:
          requires:
            - linter
            - test
          filters:
            branches:
              only: main
